jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Site\CoreBundle\Entity\UserConfigInfo:
            encode_as_base64: false
            algorithm: md5
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        webservice:
            id: db_user_provider
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/(demo/secured)/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        gallery_area:
            pattern: ^/(gallery)/
            ipb13_sec: true

    access_control:
        - { path: ^/gallery, roles: ROLE_GAL_SHOW }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
