parameters:
    db_user_provider.class: Site\CoreBundle\Security\User\DBUserProvider
#    site_common.example.class: Site\CoreBundle\Example

services:
#    site_common.example:
#        class: %site_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    db_user_provider:
        class: "%db_user_provider.class%"
        arguments: [@doctrine.orm.entity_manager]
    ipb13_sec.security.authentication.provider:
        class:  Site\CoreBundle\Security\Authentication\Provider\AuthProvider
        arguments: ['', @monolog.logger]
    ipb13_sec.security.authentication.listener:
        class:  Site\CoreBundle\Security\Firewall\AuthListener
        arguments: [@security.context, @security.authentication.manager]            
